#include <bits/stdc++.h>
using namespace std;

int solve(string &s)
{

    int n = s.size();

    // We can only do two ops: Remove the first char or remove the secodn char

    // Find the number of distinct non empty strings that can be generated by applying the ops on the string any number of times
}

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    int t;
    cin >> t;
    while (t--)
    {
    }
    return 0;
}