#include<bits/stdc++.h>
using namespace std;

string generateString(string s1, string s2)
{
    int n = s1.size(),m = s2.size();

    /*

    word of length n+m-1 is generated by s1 and s2 if : 
    if s[i] == 'T', substring of word with size m 
    
    */

}

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    string s1 = "TFTF", s2 = "ab";
    cout<<generateString(s1,s2)<<endl;
    return 0;
}